export enum BinaryOperator {
  Add = "+",
  BitAnd = "&",
  BitOr = "|",
  BitXor = "^",
  Divide = "/",
  Equals = "==",
  Greater = ">",
  InstanceOf = "instanceof",
  NotEquals = "!=",
  LegacyAdd = "add",
  LeftShift = "<<",
  Less = "<",
  Multiply = "*",
  Remainder = "%",
  SignedRightShift = ">>",
  Subtract = "-",
  StrictEquals = "===",
  StrictNotEquals = "!==",
  UnsignedRightShift = ">>>",
}
